### ISSUE TITLE
angular 1.2.x support?

### ISSUE THREAD

**Issue by kukac7** [stevermeister/angular-flipclock#1]
Hi,

Exactly this plugin's looking for the angular version.
I ask that works with both angular 1.2.x?

Thanks for your work!

**Comment by stevermeister** [comment]
Hi,

> I ask that works with both angular 1.2.x?

yes, sure. it's just simple directive wrapper.
should work even for 1.3

but it's still "green" so if you find any issues - you are welcome to report and contribute!
