### ISSUE TITLE
Whats the Key Word For Dependency Injection @ angular-flipclock ?

### ISSUE THREAD

**Issue by prasad47** [stevermeister/angular-flipclock#10]
Hi SteverMeister,

Iam Using Meanjs app  How can i inject angular-flip clock  as dependency in to app config File ? 

Thanks,
Prasad

**Comment by krish-ram** [comment]
You can use this directive by adding this module name. "angular-flipclock"

**Comment by prasad47** [comment]
@ Krish-ram 

ok Thanks you !!
