### ISSUE TITLE
Minification Breaks with ng 1.4.3

### ISSUE THREAD

**Issue by mattheworres** [stevermeister/angular-flipclock#11]
Hello,

Great wrapper directive you have here, thanks for providing it!

I'm able to use your directive in my 1.4.3 Angular app fine during development, but your module was the only piece of code that did not like when I minified and concatenated my vendor Javascript files together. I get the following error when I attempt to invoke the directive:

`Error: [$injector:unpr] http://errors.angularjs.org/1.4.3/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20flipClockDirective`

The error in that querystring link Angular provides is:

`Unknown provider: aProvider <- a <- flipClockDirective`

I took a look at the minified Javascript and it seems straightforward enough - but I think one of the things that may be tripping me up here is my minifier is probably looking at your unminified code and minifying it - but it might be botching it.

Is there any way you can provide a correctly minified version of your package?

Also does angular-flipclock have any known issues between ng 1.3.9 and 1.4.3 that I may be bumping up against?

Thanks again for this great wrapper. I really love Flipclock and was glad I found an Angular way to use it!

**Comment by mattheworres** [comment]
I just checked by disabling minification on your module alone (but concatenated it with all other vendor Javascript into vendor.js) and it works as intended, so the issue is with my minification script somehow breaking your module.

**Comment by stevermeister** [comment]
Hi @mattheworres , 

thank you for the feedback!
it's probably all about full and short angular DI notation, let me fix it for you

**Comment by stevermeister** [comment]
I've updated the code a bit, please check it now.

**Comment by mattheworres** [comment]
@stevermeister that did it! Thanks for the quick turnaround on fixing that, and I will apologize in return for not verifying that the new version fixed the minor issue I had.

Good stuff!!

**Comment by stevermeister** [comment]
you are welcome!
