### ISSUE TITLE
Error trying to intialize FlipClock

### ISSUE THREAD

**Issue by cwoolum** [stevermeister/angular-flipclock#12]
I'm getting TypeError: element.FlipClock is not a function when i try to initialize the FlipClock. If i switch back from the element initializer, it works though.

```
clock = new FlipClock(element, options);
//clock = element.FlipClock(options);
```

Any idea what is going on? I am using 0.7.7 of FlipClock

**Comment by stevermeister** [comment]
could you tell me please what stack of libraries do you use? 
AngularJS/jQuery versions 

and it would be nice if you create sandbox with you example that does not work

**Comment by fgenoese** [comment]
Exactly the same issue (and the same fix), calling from Cordova/Ionic.

Here is a sandbox example:
http://play.ionic.io/app/3bf58bb3c58e

Look into the JS tab, line 71/72

**Comment by stevermeister** [comment]
@fgenoese already answered. 
you need your ng-controller in a right place

**Comment by metusharv-ind** [comment]
When I try with angularjs 1.6 countdown time not goes down it up can you tell me the solution

**Comment by stevermeister** [comment]
if you provide a sandbox with broken example I'll have a look

**Comment by heidji** [comment]
1. npm i flipcounter
2. import * as FlipCounter from 'flipcounter'
3.
``` 
var clock = new FlipClock($('.your-clock'), {
// ... your options here
});
```
4. jQuery is not a function -> ok i can include that for you :)
5. __WEBPACK_IMPORTED_MODULE_3_flipclock__ is not a function
6. npm uninstall flipcounter
