### ISSUE TITLE
Get Values after Init

### ISSUE THREAD

**Issue by marcoslobo** [stevermeister/angular-flipclock#14]
Hello !! 
First of all, nice job with this !

How after initilizate I get the value of current time? I Already could start/Stop forcing with jquery .click, with the example. But now i wish that with another button click, i could get the current Time of the object. Can you please help me?
Thanks

**Comment by stevermeister** [comment]
@marcoslobo ,
thank you for feedback! 

I made a small change and now it's possible to get time in scope by calling:

```
$scope.getTime()
```

or  (for new ControllerAs syntax)

```
this.getTime()
```

please check

**Comment by marcoslobo** [comment]
Thanks for the help man, 
but who is your $scope? how do you get this object? 

Thanks

**Comment by stevermeister** [comment]
it uses the parent scope(basically the scope of parent element) and defines all the properties there

**Comment by marcoslobo** [comment]
Damn man, I'm not familiarized with Angular.
I'm using c# mvc jQuery.. and i can't find this object..

I will try to study a bit of Angular to see how I get some of this objcts..
Thanks anyway man

**Comment by stevermeister** [comment]
but why do you need angular than? :)
