### ISSUE TITLE
Cannot start timer programatically, i.e. from inside a controller

### ISSUE THREAD

**Issue by fgenoese** [stevermeister/angular-flipclock#16]
I would like to start the timer programatically, i.e. from inside a controller. 

To do that I call "$scope.start()" within the controller code, since the directive attaches a ".start()" function to $scope. Inside my ionic app, I then get the following error: "$scope.start is not a function".

I then tried to specify the controller explicitly using ng-controller. The result is that nothing happens, see here:
http://play.ionic.io/app/2870884ee70f

**Comment by stevermeister** [comment]
ng-controller should wrap all the elements with widget functions:
http://play.ionic.io/app/ec744e140c5d
