### ISSUE TITLE
hundreds of days - can it be displayed?

### ISSUE THREAD

**Issue by YeeP79** [stevermeister/angular-flipclock#19]
I do not want to go beyond a max time unit of days. However, when I set the flipclock to show hundreds of days, it keeps the days at 2 characters and shifts all values to the right.  For example:
Clock should read:
900 days 14 hours 22 minutes 35 seconds

Instead it reads:
90 days, 01 hours 42 minutes 235 seconds (with the 35 counting down)

Is there a setting to allow 3 character days?

Thank you

**Comment by stevermeister** [comment]
@YeeP79 
**angular-flipclock** is just a wrapper for [flipclock](http://flipclockjs.com/) library.
could you acheave what you are requesting with pure library? if yes - please provide me an example in sandbox - I'll try to help you with **angular-flipclock** implementation
