### ISSUE TITLE
Create a countdown with default value?

### ISSUE THREAD

**Issue by SaeedHassanvand** [stevermeister/angular-flipclock#20]
How i can create a countdown flip clock?
Can you help me?

**Comment by stevermeister** [comment]
angular-flipclock is just an angular wrapper for flipclock, so you need to look for a solution for flipclock and then use it for angular-flipclock, 
for example:

https://stackoverflow.com/a/25961131/274500

**Comment by esteban-serfe** [comment]
See #21 for possible solution

**Comment by stevermeister** [comment]
👍
