### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by kukac7** [stevermeister/angular-flipclock#3]
Please be documentation. :wink:

**Comment by stevermeister** [comment]
I would really appreciate if you help me with this :)

**Comment by kukac7** [comment]
How do I configure?
How do I use the callbacks?

Pls help! :smile:

**Comment by stevermeister** [comment]
it should be easy:

```
<flip-clock autostart="false" ></flip-clock>
```

what options do you want to use?

**Comment by kukac7** [comment]
for example, the time.

**Comment by stevermeister** [comment]
```
 $scope.setTime()
```

if you provide me example in pure plugin -> I  could show you how to do it with Angular wrapper

**Comment by kukac7** [comment]
check this out: http://plnkr.co/edit/eRhTyLabzYBkd7Z6isoB?p=preview

**Comment by stevermeister** [comment]
thank you for the sandbox.
1) I've fixed method call (thank you for pointing this out)
2) you can call method only after directive-controller init

please look
http://plnkr.co/edit/MMFA2R9QpieFVVjAEffQ?p=preview

**Comment by stevermeister** [comment]
one more example
http://plnkr.co/edit/K8uID54Ni3boCrU92LFe?p=preview

**Comment by kukac7** [comment]
thank you!
work without the second parameter. :wink: 
http://plnkr.co/edit/eRhTyLabzYBkd7Z6isoB?p=preview

**Comment by stevermeister** [comment]
great!

**Comment by marcoslobo** [comment]
Hello !! 
First of all, nice job with this !

How after initilizate I get the value of current time? Can you please help me? 
Thanks

**Comment by Xsmael** [comment]
These plunker examples are no longer working.... :/

**Comment by stevermeister** [comment]
that could be last change was 3 years ago, are you still using AngularJS and have not migrated to new Angular?

**Comment by Xsmael** [comment]
Yes, AngularJS is still maintained btw, and i didnt really like the way things work in Angular...

**Comment by stevermeister** [comment]
you are welcome to contribute to this project then
