### ISSUE TITLE
How do you start the clock from the controller?

### ISSUE THREAD

**Issue by ashleydavis** [stevermeister/angular-flipclock#5]
I get how to set options and callbacks.

There doesn't seem to be any documentation or examples on how to call the functions from a controller (eg the app controller).

How do I do this?

**Comment by Massad** [comment]
Adding to this issue that the method $scope.setTime(3600); is not working.

**Comment by Massad** [comment]
I solved it temporary by passing the time in scope in the directive:

http://pastebin.com/yA0V4uxU

and added `<flip-clock time="3600"></flip-clock>`

**Comment by stevermeister** [comment]
@Massad , could you please provide example of you code somewhere in jsfiddle?
I'll make it work from box

**Comment by Massad** [comment]
http://jsfiddle.net/OmarMassad/exk2nr3w/

Added an example of how to add the time from the controller too.

**Comment by ashleydavis** [comment]
I really want to be able to call start/stop/etc functions to start and stop the clock. I'm using the original FlipClock now anyway because there doesn't seem to be anyway to do this with your directive.

**Comment by Massad** [comment]
Here's another example of how you can set the time, start, stop the clock from your controller.

http://jsfiddle.net/OmarMassad/exk2nr3w/7/

Hope it's useful.

**Comment by ashleydavis** [comment]
I was hoping to call functions, rather than set variables, but thanks for trying to help.

**Comment by Massad** [comment]
You can play with the directive to make that happen and you're most welcome.

**Comment by stevermeister** [comment]
@Massad 
I've updated your example, don't see any difficulty to run methods. 
http://jsfiddle.net/STEVER/4tdxw3km/

@ashleydavis ,
please have a look too.

Let me know if it does not work for you.

**Comment by ashleydavis** [comment]
So you are binding the methods to the parent scope? Thanks that's all I need to know.

You should release this as a bower component.

**Comment by stevermeister** [comment]
> You should release this as a bower component.

It should be already there, please check
