### ISSUE TITLE
countDown setting.

### ISSUE THREAD

**Issue by krish-ram** [stevermeister/angular-flipclock#8]
Want to use this for a countdown timer. 

"flipClock clockFace='DailyCounter'" doesn't seem to work. Need to do a countDown from a day and show it in format of DailyCounter. Can you please help with any documentation?

**Comment by pleminh** [comment]
You must use 
`<flip-clock clock-face="DailyCounter"></flip-clock>`

**Comment by krish-ram** [comment]
Hi @pleminh , that doesn't seem to work.

**Comment by stevermeister** [comment]
@krish-ram , 
could you provide a fiddle for pure clockFace usage please?

**Comment by krish-ram** [comment]
@pleminh @stevermeister works fine after the merge .Thnks
